package org.home.kinonight.model;


public enum UserState {
    AWAITING_FILM_LIST_NAME,
    AWAITING_OPTION_CHOICE,
    AWAITING_FILM_NAME,
    AWAITING_LIST_SELECTION,
    AWAITING_FILM_CHOICE,
    AWAITING_FILM_TO_DELETE,
}

