spring:
  application:
    name: kinoNight
  profiles:
    active: prod
  datasource:
    url: jdbc:postgresql://database-1.c9w26080o278.us-east-1.rds.amazonaws.com:5432/kinonight
    username: root
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

aws:
  region: us-east-1
