name: Build and push Docker image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup jdk21
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew
      - name: Setup docker build
        uses: docker/setup-buildx-action@v1
      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Extract version from VERSION file
        id: version
        run: echo "::set-output name=VERSION::$(cat VERSION)"
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: minskius/kino-night:latest,minskius/kino-night:${{ steps.version.outputs.VERSION }}
      - name: Clean up
        run: ./gradlew clean

  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: setupSHH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          docker pull minskius/kino-night:latest
          docker stop kinonight || true
          docker rm kinonight || true
          docker run -d --name kinonight minskius/kino-night:latest
        
      
